/*---------------------------------------------------------- 
MASV: N18DCAT100
HO TEN: TRẦN QUỐC TRƯỢNG
LAB: 04
NGAY: 9/17/2021
----------------------------------------------------------*/
CREATE PROC SP_SEL_ENCRYPT_NHANVIEN 
AS
	SELECT MANV, HOTEN, EMAIL, LUONG
	FROM NHANVIEN
GO

EXEC SP_SEL_ENCRYPT_NHANVIEN 

select *  from NHANVIEN






SELECT * FROM NHANVIEN
SELECT * FROM LOP
SELECT * FROM SINHVIEN

DELETE FROM SINHVIEN
DELETE FROM LOP
DELETE FROM NHANVIEN

DROP PROC SP_SEL_ENCRYPT_NHANVIEN 
